/** Nombres de icono antiguos → clase Bootstrap Icons (sin `-fill`). */
export const LEGACY_ICON_TO_BOOTSTRAP: Readonly<Record<string, string>> = {
  'arrow-path': 'arrow-clockwise',
  'arrow-right-on-rectangle': 'box-arrow-right',
  'archive-box': 'archive',
  beaker: 'capsule',
  'building-office': 'building',
  'building-office-2': 'hospital',
  cake: 'cake2',
  'calendar-days': 'calendar-week',
  'chart-bar': 'bar-chart',
  'chat-bubble-left-right': 'chat-dots',
  'check-circle': 'check-circle',
  'clipboard-document': 'clipboard',
  'clipboard-document-list': 'clipboard-data',
  clock: 'clock',
  'cog-6-tooth': 'gear',
  'document-arrow-down': 'download',
  'document-text': 'file-text',
  'file-pdf': 'file-earmark-pdf',
  'exclamation-circle': 'exclamation-circle',
  'exclamation-triangle': 'exclamation-triangle',
  eye: 'eye',
  'eye-slash': 'eye-slash',
  home: 'house',
  'lock-closed': 'lock',
  'lock-open': 'unlock',
  'magnifying-glass': 'search',
  'minus-circle': 'dash-circle',
  'paper-airplane': 'send',
  'pause-circle': 'pause-circle',
  pencil: 'pencil',
  'pencil-role': 'pencil-square',
  phone: 'telephone',
  'play-circle': 'play-circle',
  'plus-circle': 'plus-circle',
  printer: 'printer',
  'rectangle-group': 'grid-3x3-gap',
  'shield-check': 'shield-check',
  'squares-2x2': 'grid',
  'table-cells': 'table',
  trash: 'trash',
  truck: 'truck',
  'user-circle': 'person-circle',
  'user-group': 'people',
  users: 'people',
  'x-circle': 'x-circle',
  bell: 'bell',
  'box-arrow-right': 'box-arrow-right',
};

export function resolveBootstrapIconClass(name: string): string {
  const key = String(name || '').trim();
  const bi = LEGACY_ICON_TO_BOOTSTRAP[key] ?? key.replace(/_/g, '-');
  return `bi-${bi}`;
}
