#!/bin/bash
# Script de ayuda para desplegar NurseHelper

echo "🚀 Guía de Despliegue - NurseHelper"
echo "===================================="
echo ""
echo "📦 PASO 1: Subir a GitHub"
echo "-------------------------"
echo "1. Crea un repositorio en GitHub (sin README)"
echo "2. Ejecuta estos comandos:"
echo ""
echo "   git remote add origin https://github.com/kechunt/NurseHelper.git"
echo "   git add ."
echo "   git commit -m 'Initial commit: NurseHelper project'"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "🚀 PASO 2: Desplegar Frontend en Vercel"
echo "----------------------------------------"
echo "1. Ve a https://vercel.com e inicia sesión con GitHub"
echo "2. Click en 'Add New Project'"
echo "3. Selecciona tu repositorio"
echo "4. Configuración:"
echo "   - Root Directory: frontend"
echo "   - Build Command: npm run build"
echo "   - Output Directory: dist/NurseHelper/browser"
echo ""
echo "⚠️  IMPORTANTE:"
echo "   - Actualiza environment.prod.ts con la URL de tu backend en Railway"
echo "   - Configura las variables de entorno en Vercel si las necesitas"
echo ""
