import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateAdministrationHistoryTable1764746137897 implements MigrationInterface {
    name = 'CreateAdministrationHistoryTable1764746137897'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`schedules\` DROP FOREIGN KEY \`schedules_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`schedules\` DROP FOREIGN KEY \`schedules_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`beds\` DROP FOREIGN KEY \`beds_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`beds\` DROP FOREIGN KEY \`fk_beds_patients\``);
        await queryRunner.query(`ALTER TABLE \`nurse_shifts\` DROP FOREIGN KEY \`FK_nurse_shifts_nurse\``);
        await queryRunner.query(`ALTER TABLE \`nurse_shifts\` DROP FOREIGN KEY \`FK_nurse_shifts_shift\``);
        await queryRunner.query(`ALTER TABLE \`nurse_shifts\` DROP FOREIGN KEY \`nurse_shifts_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`nurse_shifts\` DROP FOREIGN KEY \`nurse_shifts_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`medication_requests\` DROP FOREIGN KEY \`medication_requests_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`medication_requests\` DROP FOREIGN KEY \`medication_requests_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`delivery_history\` DROP FOREIGN KEY \`delivery_history_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`delivery_history\` DROP FOREIGN KEY \`delivery_history_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`delivery_history\` DROP FOREIGN KEY \`delivery_history_ibfk_3\``);
        await queryRunner.query(`ALTER TABLE \`delivery_history\` DROP FOREIGN KEY \`delivery_history_ibfk_4\``);
        await queryRunner.query(`DROP INDEX \`email\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_USER_EMAIL\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_USER_ROLE\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_USER_USERNAME\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`username\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`assignedToId\` ON \`schedules\``);
        await queryRunner.query(`DROP INDEX \`patientId\` ON \`schedules\``);
        await queryRunner.query(`DROP INDEX \`areaId\` ON \`beds\``);
        await queryRunner.query(`DROP INDEX \`unique_bed_area\` ON \`beds\``);
        await queryRunner.query(`DROP INDEX \`type\` ON \`shifts\``);
        await queryRunner.query(`DROP INDEX \`idx_nurse_week\` ON \`nurse_shifts\``);
        await queryRunner.query(`DROP INDEX \`idx_shift\` ON \`nurse_shifts\``);
        await queryRunner.query(`DROP INDEX \`idx_unique_nurse_day_week\` ON \`nurse_shifts\``);
        await queryRunner.query(`DROP INDEX \`idx_week_start\` ON \`nurse_shifts\``);
        await queryRunner.query(`DROP INDEX \`unique_medication_dosage\` ON \`medications\``);
        await queryRunner.query(`DROP INDEX \`idx_created\` ON \`medication_requests\``);
        await queryRunner.query(`DROP INDEX \`idx_requested_by\` ON \`medication_requests\``);
        await queryRunner.query(`DROP INDEX \`idx_status\` ON \`medication_requests\``);
        await queryRunner.query(`DROP INDEX \`medicationId\` ON \`medication_requests\``);
        await queryRunner.query(`DROP INDEX \`requestId\` ON \`medication_requests\``);
        await queryRunner.query(`DROP INDEX \`deliveredById\` ON \`delivery_history\``);
        await queryRunner.query(`DROP INDEX \`deliveryId\` ON \`delivery_history\``);
        await queryRunner.query(`DROP INDEX \`idx_delivered_at\` ON \`delivery_history\``);
        await queryRunner.query(`DROP INDEX \`idx_medication\` ON \`delivery_history\``);
        await queryRunner.query(`DROP INDEX \`idx_requested_by\` ON \`delivery_history\``);
        await queryRunner.query(`DROP INDEX \`requestId\` ON \`delivery_history\``);
        await queryRunner.query(`CREATE TABLE \`administration_history\` (\`id\` int NOT NULL AUTO_INCREMENT, \`patientId\` int NOT NULL, \`scheduleId\` int NULL, \`administeredById\` int NOT NULL, \`status\` enum ('administered', 'not_administered', 'missed') NOT NULL DEFAULT 'administered', \`type\` varchar(50) NOT NULL, \`description\` text NOT NULL, \`medication\` text NULL, \`dosage\` text NULL, \`scheduledTime\` datetime NOT NULL, \`administeredAt\` datetime NULL, \`notes\` text NULL, \`reasonNotAdministered\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD UNIQUE INDEX \`IDX_fe0bb3f6520ee0469504521e71\` (\`username\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`role\` \`role\` enum ('admin', 'nurse', 'supervisor', 'pharmacy') NOT NULL DEFAULT 'nurse'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`isActive\` \`isActive\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`schedules\` CHANGE \`type\` \`type\` enum ('medication', 'check', 'treatment', 'other') NOT NULL DEFAULT 'other'`);
        await queryRunner.query(`ALTER TABLE \`schedules\` CHANGE \`status\` \`status\` enum ('pending', 'completed', 'missed', 'cancelled') NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`schedules\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`schedules\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`schedules\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`schedules\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`patients\` CHANGE \`isActive\` \`isActive\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`patients\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`patients\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`patients\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`patients\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`beds\` ADD UNIQUE INDEX \`IDX_6a73257fde0c2e921a3ffa580c\` (\`patientId\`)`);
        await queryRunner.query(`ALTER TABLE \`beds\` CHANGE \`isActive\` \`isActive\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`beds\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`beds\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`beds\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`beds\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`areas\` CHANGE \`isActive\` \`isActive\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`areas\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`areas\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`areas\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`areas\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`shifts\` ADD UNIQUE INDEX \`IDX_3fb0802020ebc0d97decf29ffc\` (\`type\`)`);
        await queryRunner.query(`ALTER TABLE \`shifts\` CHANGE \`isActive\` \`isActive\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`shifts\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`shifts\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`shifts\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`shifts\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`nurse_shifts\` CHANGE \`dayOfWeek\` \`dayOfWeek\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`nurse_shifts\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`nurse_shifts\` CHANGE \`updatedAt\` \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`medications\` CHANGE \`stock\` \`stock\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`medications\` CHANGE \`minStock\` \`minStock\` int NOT NULL DEFAULT '50'`);
        await queryRunner.query(`ALTER TABLE \`medications\` CHANGE \`location\` \`location\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`medications\` CHANGE \`status\` \`status\` enum ('available', 'low_stock', 'out_of_stock', 'expired') NOT NULL DEFAULT 'available'`);
        await queryRunner.query(`ALTER TABLE \`medications\` CHANGE \`isActive\` \`isActive\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`medications\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`medications\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`medications\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`medications\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`medication_requests\` ADD UNIQUE INDEX \`IDX_71ebf33c2d1da48c5c6f60e8b7\` (\`requestId\`)`);
        await queryRunner.query(`ALTER TABLE \`medication_requests\` CHANGE \`patientsInfo\` \`patientsInfo\` json NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`medication_requests\` CHANGE \`status\` \`status\` enum ('pending', 'in_preparation', 'ready', 'delivered', 'cancelled') NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`medication_requests\` CHANGE \`priority\` \`priority\` enum ('low', 'normal', 'high', 'urgent') NOT NULL DEFAULT 'normal'`);
        await queryRunner.query(`ALTER TABLE \`medication_requests\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`medication_requests\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`medication_requests\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`medication_requests\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`delivery_history\` ADD UNIQUE INDEX \`IDX_e76f3741721f1eb52c54658fbe\` (\`deliveryId\`)`);
        await queryRunner.query(`ALTER TABLE \`delivery_history\` CHANGE \`patients\` \`patients\` json NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`delivery_history\` DROP COLUMN \`deliveredAt\``);
        await queryRunner.query(`ALTER TABLE \`delivery_history\` ADD \`deliveredAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\` (\`email\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_6a73257fde0c2e921a3ffa580c\` ON \`beds\` (\`patientId\`)`);
        await queryRunner.query(`ALTER TABLE \`schedules\` ADD CONSTRAINT \`FK_3b662d86d93c5febacaf65417d6\` FOREIGN KEY (\`patientId\`) REFERENCES \`patients\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`schedules\` ADD CONSTRAINT \`FK_f2a6ccc2f5105c830785bfbc15a\` FOREIGN KEY (\`assignedToId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`beds\` ADD CONSTRAINT \`FK_db8851fd2d3e07401e92b333cc2\` FOREIGN KEY (\`areaId\`) REFERENCES \`areas\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`beds\` ADD CONSTRAINT \`FK_6a73257fde0c2e921a3ffa580c3\` FOREIGN KEY (\`patientId\`) REFERENCES \`patients\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`nurse_shifts\` ADD CONSTRAINT \`FK_a550a13d652729289491f3b1346\` FOREIGN KEY (\`nurseId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`nurse_shifts\` ADD CONSTRAINT \`FK_3b0a642f220e9c03c66993c1c82\` FOREIGN KEY (\`shiftId\`) REFERENCES \`shifts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`medication_requests\` ADD CONSTRAINT \`FK_74f2775d664da8249d5360b9887\` FOREIGN KEY (\`requestedById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`medication_requests\` ADD CONSTRAINT \`FK_a4d71d00b095d0323cf9b796ab0\` FOREIGN KEY (\`medicationId\`) REFERENCES \`medications\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`delivery_history\` ADD CONSTRAINT \`FK_b2621fcbd5cb849fe20004b741c\` FOREIGN KEY (\`requestId\`) REFERENCES \`medication_requests\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`delivery_history\` ADD CONSTRAINT \`FK_fefa42e5726938182256188f027\` FOREIGN KEY (\`medicationId\`) REFERENCES \`medications\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`delivery_history\` ADD CONSTRAINT \`FK_8979e082c9a23ad7308b2bdfbdb\` FOREIGN KEY (\`requestedById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`delivery_history\` ADD CONSTRAINT \`FK_dbbda19d7edc71b7688447e15b3\` FOREIGN KEY (\`deliveredById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`administration_history\` ADD CONSTRAINT \`FK_48e48cc0f3ead3c6022b8a99038\` FOREIGN KEY (\`patientId\`) REFERENCES \`patients\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`administration_history\` ADD CONSTRAINT \`FK_f239d1e72944f5ab4b0a7ceb3f7\` FOREIGN KEY (\`scheduleId\`) REFERENCES \`schedules\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`administration_history\` ADD CONSTRAINT \`FK_7094a29ddadfe7b54e0f5600c21\` FOREIGN KEY (\`administeredById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`administration_history\` DROP FOREIGN KEY \`FK_7094a29ddadfe7b54e0f5600c21\``);
        await queryRunner.query(`ALTER TABLE \`administration_history\` DROP FOREIGN KEY \`FK_f239d1e72944f5ab4b0a7ceb3f7\``);
        await queryRunner.query(`ALTER TABLE \`administration_history\` DROP FOREIGN KEY \`FK_48e48cc0f3ead3c6022b8a99038\``);
        await queryRunner.query(`ALTER TABLE \`delivery_history\` DROP FOREIGN KEY \`FK_dbbda19d7edc71b7688447e15b3\``);
        await queryRunner.query(`ALTER TABLE \`delivery_history\` DROP FOREIGN KEY \`FK_8979e082c9a23ad7308b2bdfbdb\``);
        await queryRunner.query(`ALTER TABLE \`delivery_history\` DROP FOREIGN KEY \`FK_fefa42e5726938182256188f027\``);
        await queryRunner.query(`ALTER TABLE \`delivery_history\` DROP FOREIGN KEY \`FK_b2621fcbd5cb849fe20004b741c\``);
        await queryRunner.query(`ALTER TABLE \`medication_requests\` DROP FOREIGN KEY \`FK_a4d71d00b095d0323cf9b796ab0\``);
        await queryRunner.query(`ALTER TABLE \`medication_requests\` DROP FOREIGN KEY \`FK_74f2775d664da8249d5360b9887\``);
        await queryRunner.query(`ALTER TABLE \`nurse_shifts\` DROP FOREIGN KEY \`FK_3b0a642f220e9c03c66993c1c82\``);
        await queryRunner.query(`ALTER TABLE \`nurse_shifts\` DROP FOREIGN KEY \`FK_a550a13d652729289491f3b1346\``);
        await queryRunner.query(`ALTER TABLE \`beds\` DROP FOREIGN KEY \`FK_6a73257fde0c2e921a3ffa580c3\``);
        await queryRunner.query(`ALTER TABLE \`beds\` DROP FOREIGN KEY \`FK_db8851fd2d3e07401e92b333cc2\``);
        await queryRunner.query(`ALTER TABLE \`schedules\` DROP FOREIGN KEY \`FK_f2a6ccc2f5105c830785bfbc15a\``);
        await queryRunner.query(`ALTER TABLE \`schedules\` DROP FOREIGN KEY \`FK_3b662d86d93c5febacaf65417d6\``);
        await queryRunner.query(`DROP INDEX \`REL_6a73257fde0c2e921a3ffa580c\` ON \`beds\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`ALTER TABLE \`delivery_history\` DROP COLUMN \`deliveredAt\``);
        await queryRunner.query(`ALTER TABLE \`delivery_history\` ADD \`deliveredAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`delivery_history\` CHANGE \`patients\` \`patients\` json NOT NULL COMMENT 'Array de nombres de pacientes'`);
        await queryRunner.query(`ALTER TABLE \`delivery_history\` DROP INDEX \`IDX_e76f3741721f1eb52c54658fbe\``);
        await queryRunner.query(`ALTER TABLE \`medication_requests\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`medication_requests\` ADD \`updatedAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`medication_requests\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`medication_requests\` ADD \`createdAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`medication_requests\` CHANGE \`priority\` \`priority\` enum ('low', 'normal', 'high', 'urgent') NULL DEFAULT 'normal'`);
        await queryRunner.query(`ALTER TABLE \`medication_requests\` CHANGE \`status\` \`status\` enum ('pending', 'in_preparation', 'ready', 'delivered', 'cancelled') NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`medication_requests\` CHANGE \`patientsInfo\` \`patientsInfo\` json NOT NULL COMMENT 'Array de pacientes con sus horarios'`);
        await queryRunner.query(`ALTER TABLE \`medication_requests\` DROP INDEX \`IDX_71ebf33c2d1da48c5c6f60e8b7\``);
        await queryRunner.query(`ALTER TABLE \`medications\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`medications\` ADD \`updatedAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`medications\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`medications\` ADD \`createdAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`medications\` CHANGE \`isActive\` \`isActive\` tinyint NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`medications\` CHANGE \`status\` \`status\` enum ('available', 'low_stock', 'out_of_stock', 'expired') NULL DEFAULT 'available'`);
        await queryRunner.query(`ALTER TABLE \`medications\` CHANGE \`location\` \`location\` varchar(50) NULL COMMENT 'Ubicación física en farmacia'`);
        await queryRunner.query(`ALTER TABLE \`medications\` CHANGE \`minStock\` \`minStock\` int NULL DEFAULT '50'`);
        await queryRunner.query(`ALTER TABLE \`medications\` CHANGE \`stock\` \`stock\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`nurse_shifts\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`nurse_shifts\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`nurse_shifts\` CHANGE \`dayOfWeek\` \`dayOfWeek\` int NOT NULL COMMENT '0=Domingo, 1=Lunes, 2=Martes, 3=Miércoles, 4=Jueves, 5=Viernes, 6=Sábado'`);
        await queryRunner.query(`ALTER TABLE \`shifts\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`shifts\` ADD \`updatedAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`shifts\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`shifts\` ADD \`createdAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`shifts\` CHANGE \`isActive\` \`isActive\` tinyint NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`shifts\` DROP INDEX \`IDX_3fb0802020ebc0d97decf29ffc\``);
        await queryRunner.query(`ALTER TABLE \`areas\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`areas\` ADD \`updatedAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`areas\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`areas\` ADD \`createdAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`areas\` CHANGE \`isActive\` \`isActive\` tinyint NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`beds\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`beds\` ADD \`updatedAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`beds\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`beds\` ADD \`createdAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`beds\` CHANGE \`isActive\` \`isActive\` tinyint NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`beds\` DROP INDEX \`IDX_6a73257fde0c2e921a3ffa580c\``);
        await queryRunner.query(`ALTER TABLE \`patients\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`patients\` ADD \`updatedAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`patients\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`patients\` ADD \`createdAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`patients\` CHANGE \`isActive\` \`isActive\` tinyint NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`schedules\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`schedules\` ADD \`updatedAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`schedules\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`schedules\` ADD \`createdAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`schedules\` CHANGE \`status\` \`status\` enum ('pending', 'completed', 'missed', 'cancelled') NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`schedules\` CHANGE \`type\` \`type\` enum ('medication', 'check', 'treatment', 'other') NULL DEFAULT 'other'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updatedAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`createdAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`isActive\` \`isActive\` tinyint NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`role\` \`role\` enum ('admin', 'nurse', 'supervisor', 'pharmacy') NULL DEFAULT 'nurse'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP INDEX \`IDX_fe0bb3f6520ee0469504521e71\``);
        await queryRunner.query(`DROP TABLE \`administration_history\``);
        await queryRunner.query(`CREATE INDEX \`requestId\` ON \`delivery_history\` (\`requestId\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_requested_by\` ON \`delivery_history\` (\`requestedById\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_medication\` ON \`delivery_history\` (\`medicationId\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_delivered_at\` ON \`delivery_history\` (\`deliveredAt\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`deliveryId\` ON \`delivery_history\` (\`deliveryId\`)`);
        await queryRunner.query(`CREATE INDEX \`deliveredById\` ON \`delivery_history\` (\`deliveredById\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`requestId\` ON \`medication_requests\` (\`requestId\`)`);
        await queryRunner.query(`CREATE INDEX \`medicationId\` ON \`medication_requests\` (\`medicationId\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_status\` ON \`medication_requests\` (\`status\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_requested_by\` ON \`medication_requests\` (\`requestedById\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_created\` ON \`medication_requests\` (\`createdAt\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`unique_medication_dosage\` ON \`medications\` (\`name\`, \`dosage\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_week_start\` ON \`nurse_shifts\` (\`weekStartDate\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`idx_unique_nurse_day_week\` ON \`nurse_shifts\` (\`nurseId\`, \`dayOfWeek\`, \`weekStartDate\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_shift\` ON \`nurse_shifts\` (\`shiftId\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_nurse_week\` ON \`nurse_shifts\` (\`nurseId\`, \`weekStartDate\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`type\` ON \`shifts\` (\`type\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`unique_bed_area\` ON \`beds\` (\`bedNumber\`, \`areaId\`)`);
        await queryRunner.query(`CREATE INDEX \`areaId\` ON \`beds\` (\`areaId\`)`);
        await queryRunner.query(`CREATE INDEX \`patientId\` ON \`schedules\` (\`patientId\`)`);
        await queryRunner.query(`CREATE INDEX \`assignedToId\` ON \`schedules\` (\`assignedToId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`username\` ON \`users\` (\`username\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_USER_USERNAME\` ON \`users\` (\`username\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_USER_ROLE\` ON \`users\` (\`role\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_USER_EMAIL\` ON \`users\` (\`email\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`email\` ON \`users\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`delivery_history\` ADD CONSTRAINT \`delivery_history_ibfk_4\` FOREIGN KEY (\`deliveredById\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`delivery_history\` ADD CONSTRAINT \`delivery_history_ibfk_3\` FOREIGN KEY (\`requestedById\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`delivery_history\` ADD CONSTRAINT \`delivery_history_ibfk_2\` FOREIGN KEY (\`medicationId\`) REFERENCES \`medications\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`delivery_history\` ADD CONSTRAINT \`delivery_history_ibfk_1\` FOREIGN KEY (\`requestId\`) REFERENCES \`medication_requests\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`medication_requests\` ADD CONSTRAINT \`medication_requests_ibfk_2\` FOREIGN KEY (\`medicationId\`) REFERENCES \`medications\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`medication_requests\` ADD CONSTRAINT \`medication_requests_ibfk_1\` FOREIGN KEY (\`requestedById\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`nurse_shifts\` ADD CONSTRAINT \`nurse_shifts_ibfk_2\` FOREIGN KEY (\`shiftId\`) REFERENCES \`shifts\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`nurse_shifts\` ADD CONSTRAINT \`nurse_shifts_ibfk_1\` FOREIGN KEY (\`nurseId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`nurse_shifts\` ADD CONSTRAINT \`FK_nurse_shifts_shift\` FOREIGN KEY (\`shiftId\`) REFERENCES \`shifts\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`nurse_shifts\` ADD CONSTRAINT \`FK_nurse_shifts_nurse\` FOREIGN KEY (\`nurseId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`beds\` ADD CONSTRAINT \`fk_beds_patients\` FOREIGN KEY (\`patientId\`) REFERENCES \`patients\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`beds\` ADD CONSTRAINT \`beds_ibfk_1\` FOREIGN KEY (\`areaId\`) REFERENCES \`areas\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`schedules\` ADD CONSTRAINT \`schedules_ibfk_2\` FOREIGN KEY (\`assignedToId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`schedules\` ADD CONSTRAINT \`schedules_ibfk_1\` FOREIGN KEY (\`patientId\`) REFERENCES \`patients\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
