export const WEBHOOK_EVENT_CATALOG = [
  { event: 'auth.login.success', label: 'Inicio de sesión exitoso' },
  { event: 'auth.login.failed', label: 'Inicio de sesión fallido' },
  { event: 'auth.logout', label: 'Cierre de sesión' },
  { event: 'patient.created', label: 'Paciente creado' },
  { event: 'patient.updated', label: 'Paciente actualizado' },
  { event: 'patient.deleted', label: 'Paciente eliminado' },
  { event: 'patient.observation.added', label: 'Observación clínica agregada' },
  { event: 'medication.added', label: 'Medicamento agregado' },
  { event: 'medication.suspended', label: 'Medicamento suspendido' },
  { event: 'medication.deleted', label: 'Medicamento eliminado' },
  { event: 'medication.reactivated', label: 'Medicamento reactivado' },
  { event: 'medication.administration.recorded', label: 'Administración registrada' },
  { event: 'medication.administration.missed', label: 'Administración omitida' },
  { event: 'user.created', label: 'Usuario creado' },
  { event: 'user.updated', label: 'Usuario actualizado' },
  { event: 'user.deleted', label: 'Usuario eliminado' },
  { event: 'user.role.changed', label: 'Rol de usuario cambiado' },
  { event: 'backup.created', label: 'Respaldo creado' },
  { event: 'backup.restored', label: 'Respaldo restaurado' },
  { event: 'security.permission.denied', label: 'Permiso denegado' },
  { event: 'security.rate_limit.exceeded', label: 'Límite de solicitudes excedido' },
  { event: 'security.suspicious_activity', label: 'Actividad sospechosa' },
] as const;

export type WebhookEventName = (typeof WEBHOOK_EVENT_CATALOG)[number]['event'];

export const AUDIT_ACTION_WEBHOOK_EVENTS: Readonly<Record<string, WebhookEventName>> = {
  LOGIN_SUCCESS: 'auth.login.success',
  LOGIN_FAILED: 'auth.login.failed',
  LOGOUT: 'auth.logout',
  PATIENT_CREATED: 'patient.created',
  PATIENT_UPDATED: 'patient.updated',
  PATIENT_DELETED: 'patient.deleted',
  PATIENT_OBSERVATION_ADDED: 'patient.observation.added',
  MEDICATION_ADDED: 'medication.added',
  MEDICATION_SUSPENDED: 'medication.suspended',
  MEDICATION_DELETED: 'medication.deleted',
  MEDICATION_REACTIVATED: 'medication.reactivated',
  ADMINISTRATION_RECORDED: 'medication.administration.recorded',
  ADMINISTRATION_MISSED: 'medication.administration.missed',
  USER_CREATED: 'user.created',
  USER_UPDATED: 'user.updated',
  USER_DELETED: 'user.deleted',
  USER_ROLE_CHANGED: 'user.role.changed',
  BACKUP_CREATED: 'backup.created',
  BACKUP_RESTORED: 'backup.restored',
  PERMISSION_DENIED: 'security.permission.denied',
  RATE_LIMIT_EXCEEDED: 'security.rate_limit.exceeded',
  SUSPICIOUS_ACTIVITY: 'security.suspicious_activity',
};
