import type { NurseDashboardOverlaysStackVm } from './nurse-dashboard-overlays-stack/nurse-dashboard-overlays-stack.vm';

/** Estado del padre necesario para sincronizar el VM del stack de overlays. */
export interface NurseDashboardOverlaysStateSource {
  pharmacyPatientsModalMed: NurseDashboardOverlaysStackVm['pharmacyPatientsModalMed'];
  selectedTaskForNotCompleted: NurseDashboardOverlaysStackVm['selectedTaskForNotCompleted'];
  selectedPatient: NurseDashboardOverlaysStackVm['selectedPatient'];
  showPatientModal: boolean;
  activeTab: NurseDashboardOverlaysStackVm['activeTab'];
  newDiagnosisNote: string;
  newMedicalObservationNote: string;
  newAllergiesNote: string;
  newSpecialNeedsNote: string;
  newGeneralObservationNote: string;
  isSavingObservation: boolean;
  historyFilter: NurseDashboardOverlaysStackVm['historyFilter'];
  historyOutcomeFilter: NurseDashboardOverlaysStackVm['historyOutcomeFilter'];
  historyEditRecord: NurseDashboardOverlaysStackVm['historyEditRecord'];
  scheduleEditContext: NurseDashboardOverlaysStackVm['scheduleEditContext'];
  historyDetailRecord: NurseDashboardOverlaysStackVm['historyDetailRecord'];
  medicationDayDetailView: NurseDashboardOverlaysStackVm['medicationDayDetailView'];
  pendingTaskDetailModalOpen: boolean;
  pendingTaskDetail: NurseDashboardOverlaysStackVm['pendingTaskDetail'];
  showHandoverModal: boolean;
  handoverDate: NurseDashboardOverlaysStackVm['handoverDate'];
  handoverShift: NurseDashboardOverlaysStackVm['handoverShift'];
  handoverBody: string;
  handoverSaving: boolean;
  handoverCanAcknowledge: boolean;
  showNurseReportsModal: boolean;
  nurseReportsPeriodLabel: string;
  nurseReportsStartDate: string;
  nurseReportsEndDate: string;
  nurseReportsLoading: boolean;
  nurseReportsExporting: boolean;
  nurseReportsMedication: NurseDashboardOverlaysStackVm['nurseReportsMedication'];
  nurseReportsCompliance: NurseDashboardOverlaysStackVm['nurseReportsCompliance'];
  nurseReportsError: string | null;
  tasksQuickModalOpen: boolean;
  patients: NurseDashboardOverlaysStackVm['patients'];
  tasksPatientFilter: NurseDashboardOverlaysStackVm['tasksPatientFilter'];
  tasksHourFilter: NurseDashboardOverlaysStackVm['tasksHourFilter'];
  tasksGroupedByHour: NurseDashboardOverlaysStackVm['tasksGroupedByHour'];
  medicationsForPharmacy: NurseDashboardOverlaysStackVm['medicationsForPharmacy'];
  uniqueMedicationsCount: number;
  totalDosesToday: number;
  scheduleSlotsView: NurseDashboardOverlaysStackVm['scheduleSlotsView'];
  addMedicationModalOpen: boolean;
  addMedicationLockPatientSelect: boolean;
  addMedicationInitialPatientId: string;
  medicationToSuspend: NurseDashboardOverlaysStackVm['medicationToSuspend'];
  medicationToDelete: NurseDashboardOverlaysStackVm['medicationToDelete'];
  medicationToReactivate: NurseDashboardOverlaysStackVm['medicationToReactivate'];
  addTreatmentModalOpen: boolean;
  addTreatmentMode: NurseDashboardOverlaysStackVm['addTreatmentMode'];
  addTreatmentFromPatientContext: NurseDashboardOverlaysStackVm['addTreatmentFromPatientContext'];
  addTreatmentInitialPatientId: string;
  treatmentPostponeItem: NurseDashboardOverlaysStackVm['treatmentPostponeItem'];
  taskToPostpone: NurseDashboardOverlaysStackVm['taskToPostpone'];
  editBedModalBed: NurseDashboardOverlaysStackVm['editBedModalBed'];
  myBeds: NurseDashboardOverlaysStackVm['myBeds'];
  getMedicationsTodaySorted(): NurseDashboardOverlaysStackVm['medicationsSlots'];
  getTreatmentsTodaySorted(): NurseDashboardOverlaysStackVm['treatmentsSlots'];
  getFilteredHistoryFlatSorted(): NurseDashboardOverlaysStackVm['historyRecords'];
}

/** Sincroniza propiedades del VM estable sin recrear el objeto (evita `ngDoCheck`). */
export function syncNurseDashboardOverlaysStackVm(
  vm: NurseDashboardOverlaysStackVm,
  state: NurseDashboardOverlaysStateSource
): void {
  const patientName = state.selectedPatient?.name ?? null;
  vm.pharmacyPatientsModalMed = state.pharmacyPatientsModalMed;
  vm.selectedTaskForNotCompleted = state.selectedTaskForNotCompleted;
  vm.selectedPatientNameFallback = patientName;
  vm.showPatientModal = state.showPatientModal;
  vm.selectedPatient = state.selectedPatient;
  vm.activeTab = state.activeTab;
  vm.newDiagnosisNote = state.newDiagnosisNote;
  vm.newMedicalObservationNote = state.newMedicalObservationNote;
  vm.newAllergiesNote = state.newAllergiesNote;
  vm.newSpecialNeedsNote = state.newSpecialNeedsNote;
  vm.newGeneralObservationNote = state.newGeneralObservationNote;
  vm.isSavingObservation = state.isSavingObservation;
  vm.historyFilter = state.historyFilter;
  vm.historyOutcomeFilter = state.historyOutcomeFilter;
  vm.historyEditRecord = state.historyEditRecord;
  vm.scheduleEditContext = state.scheduleEditContext;
  vm.medicationsSlots = state.getMedicationsTodaySorted();
  vm.treatmentsSlots = state.getTreatmentsTodaySorted();
  vm.historyRecords = state.getFilteredHistoryFlatSorted();
  vm.historyDetailRecord = state.historyDetailRecord;
  vm.medicationDayDetailView = state.medicationDayDetailView;
  vm.pendingTaskDetailModalOpen = state.pendingTaskDetailModalOpen;
  vm.pendingTaskDetail = state.pendingTaskDetail;
  vm.showHandoverModal = state.showHandoverModal;
  vm.handoverDate = state.handoverDate;
  vm.handoverShift = state.handoverShift;
  vm.handoverBody = state.handoverBody;
  vm.handoverSaving = state.handoverSaving;
  vm.handoverCanAcknowledge = state.handoverCanAcknowledge;
  vm.showNurseReportsModal = state.showNurseReportsModal;
  vm.nurseReportsPeriodLabel = state.nurseReportsPeriodLabel;
  vm.nurseReportsStartDate = state.nurseReportsStartDate;
  vm.nurseReportsEndDate = state.nurseReportsEndDate;
  vm.nurseReportsLoading = state.nurseReportsLoading;
  vm.nurseReportsExporting = state.nurseReportsExporting;
  vm.nurseReportsMedication = state.nurseReportsMedication;
  vm.nurseReportsCompliance = state.nurseReportsCompliance;
  vm.nurseReportsError = state.nurseReportsError;
  vm.tasksQuickModalOpen = state.tasksQuickModalOpen;
  vm.patients = state.patients;
  vm.tasksPatientFilter = state.tasksPatientFilter;
  vm.tasksHourFilter = state.tasksHourFilter;
  vm.tasksGroupedByHour = state.tasksGroupedByHour;
  vm.medicationsForPharmacy = state.medicationsForPharmacy;
  vm.uniqueMedicationsCount = state.uniqueMedicationsCount;
  vm.totalDosesToday = state.totalDosesToday;
  vm.scheduleSlotsView = state.scheduleSlotsView;
  vm.addMedicationModalOpen = state.addMedicationModalOpen;
  vm.addMedicationLockPatientSelect = state.addMedicationLockPatientSelect;
  vm.addMedicationInitialPatientId = state.addMedicationInitialPatientId;
  vm.medicationToSuspend = state.medicationToSuspend;
  vm.medicationToDelete = state.medicationToDelete;
  vm.medicationToReactivate = state.medicationToReactivate;
  vm.selectedPatientNameForMedicationModals = patientName;
  vm.addTreatmentModalOpen = state.addTreatmentModalOpen;
  vm.addTreatmentMode = state.addTreatmentMode;
  vm.addTreatmentFromPatientContext = state.addTreatmentFromPatientContext;
  vm.addTreatmentInitialPatientId = state.addTreatmentInitialPatientId;
  vm.treatmentPostponeItem = state.treatmentPostponeItem;
  vm.taskToPostpone = state.taskToPostpone;
  vm.editBedModalBed = state.editBedModalBed;
  vm.myBeds = state.myBeds;
}
